### ISSUE TITLE
子节点没有全部选中，父节点可以半选联动；但是子节点全部选中后，父节点不能够全选联动

### ISSUE THREAD

**Issue by faiz-gear** [lycHub/vue-virtual-tree#10]
![WX20220325-104007](https://user-images.githubusercontent.com/70053309/160044161-a5717c51-68da-4409-bf0e-34c274f2466e.png)
![WX20220325-104021](https://user-images.githubusercontent.com/70053309/160044169-77472bc5-4c66-4cbf-a183-04ca24f8f965.png)

**Comment by lycHub** [comment]
我本地看了下没复现诶   用这个重现下吧
[demo-v4](https://stackblitz.com/edit/vue-virtual-tree-demos-bvicgw?file=src/App.vue)

**Comment by faiz-gear** [comment]
> 我本地看了下没复现诶 用这个重现下吧 [demo-v4](https://stackblitz.com/edit/vue-virtual-tree-demos-bvicgw?file=src/App.vue)
![image](https://user-images.githubusercontent.com/70053309/160085173-f2e73e96-590a-40ad-bd53-d0d452d1167b.png)

能看到吗现在

**Comment by lycHub** [comment]
已修复 更新到v4.0.7

**Comment by faiz-gear** [comment]
> 已修复 更新到v4.0.7

<img width="1661" alt="WX20220325-205755@2x" src="https://user-images.githubusercontent.com/70053309/160125849-a124ed41-97eb-4c3b-83ff-f834523248d8.png">
<img width="1675" alt="WX20220325-210232@2x" src="https://user-images.githubusercontent.com/70053309/160125856-76d0093d-41e9-4948-bff6-0929ab86242a.png">
深层级的节点如果default checked：第一个问题是父节点的父节点如果不展开，就不会是半选中状态（如图一）；第二个问题是顶层节点没有对应是半选状态（如图二）

**Comment by lycHub** [comment]
我重构了个新库： [tree](https://github.com/lycHub/ysx-library/blob/master/projects/VirtualTree/README.md)
