### ISSUE TITLE
顶层0-0的没有按理想状况实现半选

### ISSUE THREAD

**Issue by yemaozi999** [lycHub/vue-virtual-tree#11]
![GIF 2022-4-19 16-20-39](https://user-images.githubusercontent.com/16147749/163958495-06905726-530d-48e8-8f87-f451c73af263.gif)

重新展开后,  半选会变化, 变成最近一级的半选错误了 
![GIF 2022-4-19 17-00-46](https://user-images.githubusercontent.com/16147749/163969264-2aea9a50-3d2b-4d5c-b361-1418a64b2e6d.gif)

**Comment by lycHub** [comment]
我重构了个新库： [tree](https://github.com/lycHub/ysx-library/blob/master/projects/VirtualTree/README.md)
