### ISSUE TITLE
是否可以提供一个搜索功能 昨天试用了一下最后发现没有搜索功能又用了treev2

### ISSUE THREAD

**Issue by hpy0826** [lycHub/vue-virtual-tree#12]

**Comment by lycHub** [comment]
写了一个搜索树的例子：
[search demo](https://vue-tree-4gi26kh195ddd24f-1257117519.tcloudbaseapp.com/docs/tree/)

使用  @ysx-libs/vue-virtual-tree

**Comment by hpy0826** [comment]
谢谢。看了一下。思路很清晰
