### ISSUE TITLE
大神 checkedkeys 可否 双向绑定或者提供一个set的方法呢

### ISSUE THREAD

**Issue by wangwenwei** [lycHub/vue-virtual-tree#7]

**Comment by lycHub** [comment]
hello, 那几个defaultCheckedKeys等属性额，我已经完善了watch的逻辑，请先更新到v4.0.2, 用输入属性+监听事件的方式处理吧
给这几个状态属性加v-model 额  改动挺大的，可读性也不太好，这个容我想下
