### ISSUE TITLE
设置defaultCheckedKeys为某一个子节点时，父节点如果没有展开，就不会是半选状态，同时在不展开的状态下，调用getCheckedNodes也获取不到正确的值

### ISSUE THREAD

**Issue by faiz-gear** [lycHub/vue-virtual-tree#8]

**Comment by luyao514** [comment]
![Snipaste_2022-03-05_16-45-28](https://user-images.git
![Snipaste_2022-03-05_16-45-37](https://user-images.githubusercontent.com/70053309/156876062-8ae17289-3ec6-4152-b4b3-1010e3102437.png)
hubusercontent.com/70053309/156876054-aea35ddf-5b12-45a8-8ee9-ff3f106b3cce.png)

**Comment by faiz-gear** [comment]
![Snipaste_2022-03-05_16-45-28](https://user-images.githubusercontent.com/70053309/156876083-5f6a824e-22be-4caf-9876-41e0d4585ed7.png)

**Comment by faiz-gear** [comment]
![Snipaste_2022-03-05_16-45-37](https://user-images.githubusercontent.com/70053309/156876090-8d8ac8d9-0963-4274-a6a3-a197e777d11e.png)

**Comment by lycHub** [comment]
好地，请更新到v4.0.3试下

**Comment by faiz-gear** [comment]
> 好地，请更新到v4.0.3试下
![WX20220307-120840](https://user-images.githubusercontent.com/70053309/156976309-43571730-23e4-4429-9ee2-c4beccaeb008.png)

您好，这边仍然存在一个bug，调用getCheckedNodes获取到的节点，第一次是正常的，第二次会多一条相同的节点对象，并且parentKey为null

**Comment by lycHub** [comment]
> > 好地，请更新到v4.0.3试下
> > ![WX20220307-120840](https://user-images.githubusercontent.com/70053309/156976309-43571730-23e4-4429-9ee2-c4beccaeb008.png)
> 
> 您好，这边仍然存在一个bug，调用getCheckedNodes获取到的节点，第一次是正常的，第二次会多一条相同的节点对象，并且parentKey为null

已修复，请更新到v4.0.5

**Comment by faiz-gear** [comment]
好的，谢谢大佬，大佬回复和更新效率真高 👍

**Comment by faiz-gear** [comment]
> > > 好地，请更新到v4.0.3试下
> > > ![WX20220307-120840](https://user-images.githubusercontent.com/70053309/156976309-43571730-23e4-4429-9ee2-c4beccaeb008.png)
> > 
> > 
> > 您好，这边仍然存在一个bug，调用getCheckedNodes获取到的节点，第一次是正常的，第二次会多一条相同的节点对象，并且parentKey为null
> 
> 已修复，请更新到v4.0.5

这一版存在一个bug，level为1的节点不展开，getCheckedNodes获取不到该level为1的节点的checked的子节点

**Comment by lycHub** [comment]
已修复，更新到4.0.6
