### ISSUE TITLE
如果有那么一个slot 树后面的东西,可以自定义就好了

### ISSUE THREAD

**Issue by yemaozi999** [lycHub/vue-virtual-tree#9]
![image](https://user-images.githubusercontent.com/16147749/159887091-71f840b4-e2f2-4ac6-9bb8-3fb05385cdbf.png)

**Comment by yemaozi999** [comment]
https://demo.gin-vue-admin.com/#/layout/admin/authority    点击设置权限可看

**Comment by lycHub** [comment]
可参考自定义node:
(demo)[https://vue-tree-4gi26kh195ddd24f-1257117519.tcloudbaseapp.com/docs/tree/#custom-node-demo]

tip: 使用新的 @ysx-libs/vue-virtual-tree
